export enum Category {
    FOOD = 'FOOD',
    RESTAURANT = 'RESTAURANT',
    VACATION = 'VACATION',
    CLOTHING = 'CLOTHING',
    TOYS = 'TOYS',
    PHARMA = 'PHARMA',
    SPORTS = 'SPORTS',
    ELECTRONICS = 'ELECTRONICS',
    GAMING= 'GAMING'
}